apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName | lower }}
  description: ${{ values.description }}
  annotations:
    jenkins.io/job-full-name: ${{ values.componentName | lower }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
